# 并行化思想

In [1]:
import numpy as np
#普通列表方式
no_list = range(10000)
%timeit [i**2 for i in no_list]

4.32 ms ± 90.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [2]:
np_list = np.arange(10000)
%timeit np_list**2

10.8 µs ± 448 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
#NumPy数组乘法
np_list = np.ones(5) 
print(np_list)
np_list *= 5
print(np_list)
#普通列表乘法
no_list = [1,1,1,1,1]
no_list *=5
print(no_list)

[ 1.  1.  1.  1.  1.]
[ 5.  5.  5.  5.  5.]
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


## 初始化Numpy数组的方式

In [20]:
np.zeros(100) #100个0
np.zeros((3,2)) #3*2数组
np.ones(100) #100个1
np.ones((3,2))
np.empty((2,3,2)) #3维数组，数值随机

array([[[  1.17132396e-311,   2.81617418e-322],
        [  0.00000000e+000,   0.00000000e+000],
        [  2.13620671e-306,   1.33664410e+160]],

       [[  4.75874123e-090,   3.42103978e-032],
        [  1.26070997e-076,   9.58411858e+169],
        [  6.48224660e+170,   4.93432906e+257]]])

In [23]:
np.zeros_like(no_list) #根据no_list的结构生成全0数组

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])